# Generated by Django 4.1.3 on 2022-12-09 06:28

from django.db import migrations, models
import django.db.models.manager
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='direccion email')),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('apellido', models.CharField(max_length=150, unique=True)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('provincia', models.CharField(blank=True, max_length=150)),
                ('numero_telefono', models.CharField(blank=True, max_length=15)),
                ('codigo_postal', models.CharField(blank=True, max_length=12)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('nota', models.TextField(blank=True, max_length=500, verbose_name='acerca_de')),
                ('activo', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cuentas',
                'verbose_name_plural': 'Cuentas',
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
