# Generated by Django 4.1.3 on 2022-12-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_usuariobase_apellido_alter_usuariobase_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariobase',
            old_name='activo',
            new_name='is_active',
        ),
    ]
